export const ACTION_TYPES = {
  
    // goods
    GET_GOODS_START: 'GET_GOODS_START',
    GET_GOODS_SUCCESS: 'GET_GOODS_SUCCESS',
    GET_GOODS_FAILURE: 'GET_GOODS_FAILURE',

    // item
    GET_ITEM_START: 'GET_ITEM_START',
    GET_ITEM_SUCCESS: 'GET_ITEM_SUCCESS',
    GET_ITEM_FAILURE: 'GET_ITEM_FAILURE',

}